pull_request_rules:
  - name: automatic merge on CI success from dependabot
    conditions:
      - author=dependabot[bot]
      - base=develop
      - status-success=ci/circleci: test_aws_viewer
      - status-success=ci/circleci: test_shared
    actions:
      merge:
        method: merge
